/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i9knz7EXdrcBWswQTuKKjX
// Component: t6bbWH5XZ4fm

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 7v6YGoE2Zo0o/component

import { useScreenVariants as useScreenVariantsajVfn3Ya69H5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: AJVfn3Ya69h5/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: i9knz7EXdrcBWswQTuKKjX/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: t6bbWH5XZ4fm/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: k4ujBvekGioO/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: H5Yxuv6_n5vq/icon
import CrownHaloIcon from "./icons/PlasmicIcon__CrownHalo"; // plasmic-import: QESqRHbH-Tr7/icon
import LineBreakIcon from "./icons/PlasmicIcon__LineBreak"; // plasmic-import: OaJD_NBb6Nrq/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  headerSection?: Flex__<"section">;
  h1?: Flex__<"h1">;
  button?: Flex__<typeof Button>;
  aboutMeSection?: Flex__<"section">;
  h4?: Flex__<"h4">;
  portfolioSection?: Flex__<"section">;
  h6?: Flex__<"h6">;
  libertineBlendsProject?: Flex__<"div">;
  libertineCocktailBarProject?: Flex__<"div">;
  tiberiProject?: Flex__<"div">;
  whiskeriaProject?: Flex__<"div">;
  twoSchmukcs?: Flex__<"div">;
  creativeColabsProject?: Flex__<"div">;
  servicesSection?: Flex__<"section">;
  service1?: Flex__<"div">;
  rtdProductDevelopment?: Flex__<"div">;
  service2?: Flex__<"div">;
  rtdProductDevelopment2?: Flex__<"div">;
  service3?: Flex__<"div">;
  rtdProductDevelopment3?: Flex__<"div">;
  service4?: Flex__<"div">;
  rtdProductDevelopment4?: Flex__<"div">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsajVfn3Ya69H5()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"headerSection"}
            data-plasmic-override={overrides.headerSection}
            className={classNames(projectcss.all, sty.headerSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wrbg8)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__okmBy)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "desktopOnly")
                    ? "152px"
                    : "82px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_website_mobile_first/images/cocktailOnTable.png",
                  fullWidth: 304,
                  fullHeight: 214,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r6Ms5
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__s8CyR
                      )}
                    >
                      {"COCKTAIL"}
                    </h3>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__agGoN)}>
              <div className={classNames(projectcss.all, sty.freeBox__ewVxr)}>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__yB37N
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"KING"}
                      </h1>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </h3>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tpE3K)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2YIc
                    )}
                  >
                    {"Global Beverage Consultant"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zm90M
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Expert in "}</React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link___5Zlyj
                          )}
                          component={Link}
                          href={"https://test.com"}
                          platform={"nextjs"}
                        >
                          {"Ready-to-Drink Cocktails"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{", "}</React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__sARtq
                          )}
                          component={Link}
                          href={"https://test.com"}
                          platform={"nextjs"}
                        >
                          {"Bar Program Development"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{" & "}</React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link___2Cn6U
                          )}
                          component={Link}
                          href={"https://test.com"}
                          platform={"nextjs"}
                        >
                          {"Menu Curation"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dGq2T
                      )}
                    >
                      {"Let\u2019s work together"}
                    </div>
                  }
                />
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__nIRsV)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "desktopOnly")
                    ? "398px"
                    : "239px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_website_mobile_first/images/cocktailWithLemon.png",
                  fullWidth: 478,
                  fullHeight: 768,
                  aspectRatio: undefined
                }}
              />
            </div>
          </section>
          <section
            data-plasmic-name={"aboutMeSection"}
            data-plasmic-override={overrides.aboutMeSection}
            className={classNames(projectcss.all, sty.aboutMeSection)}
            id={"about-me"}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ekNw6)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___3Ol6L)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"559px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_website_mobile_first/images/profilePic.png",
                  fullWidth: 1110,
                  fullHeight: 1466,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox___6VpK3)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pAg8Q)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1ApTq
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          data-plasmic-name={"h4"}
                          data-plasmic-override={overrides.h4}
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-vKYvxi3wkDsp)" }}
                            >
                              {"ABOUT ME."}
                            </span>
                          </React.Fragment>
                        </h4>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <CrownHaloIcon
                    className={classNames(projectcss.all, sty.svg__nxJdj)}
                    role={"img"}
                  />
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fY8QO
                  )}
                >
                  {
                    "I'm an award-winning beverage consultant working globally to help brands, bars, and product developers bring their visions to life. My background spans cocktail development, production consulting, staff training, and menu design."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8ADKo
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul___4Eiz8
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__z2Cdn
                          )}
                        >
                          {"Ingredient-driven"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__yxGVr
                          )}
                        >
                          {"Technically precise\n"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__cdzBj
                          )}
                        >
                          {"Thoughtfully creative"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__d86Ak
                          )}
                        >
                          {"Comforting yet sophisticated"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___7DTs6
                          )}
                        >
                          {
                            "Always clean and minimal in design and presentation"
                          }
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rj3O
                  )}
                >
                  {
                    "I've collaborated with companies ranging from boutique producers to large-scale manufacturers, always tailoring solutions that balance form, function, and flavor."
                  }
                </div>
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"portfolioSection"}
            data-plasmic-override={overrides.portfolioSection}
            className={classNames(projectcss.all, sty.portfolioSection)}
            id={"portfolio"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wfw4L
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h6
                    data-plasmic-name={"h6"}
                    data-plasmic-override={overrides.h6}
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6
                    )}
                  >
                    {"PORTFOLIO / RECENT"}
                  </h6>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gzkOn
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__brndw
                    )}
                  >
                    {"PROJECTS"}
                  </h3>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__zcNq5)}>
              <div
                data-plasmic-name={"libertineBlendsProject"}
                data-plasmic-override={overrides.libertineBlendsProject}
                className={classNames(
                  projectcss.all,
                  sty.libertineBlendsProject
                )}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__nWh6E)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/stackedCans.png",
                    fullWidth: 632,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__kBwyl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cmr7P
                    )}
                  >
                    {"RTD Cocktail Development"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lSzin
                  )}
                >
                  {"Creative Collaborations"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__flAd
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__rOGr9
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__hbZDo
                          )}
                        >
                          {"Concept Creation"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__qn6K1
                          )}
                        >
                          {"Recipe Creation"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__qYqzs
                          )}
                        >
                          {"Recipe Scaling"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__sFk6
                          )}
                        >
                          {"Production"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"libertineCocktailBarProject"}
                data-plasmic-override={overrides.libertineCocktailBarProject}
                className={classNames(
                  projectcss.all,
                  sty.libertineCocktailBarProject
                )}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cd0Z0)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/barAndTables.png",
                    fullWidth: 632,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8AWe)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xXDx0
                    )}
                  >
                    {"Bar Programs"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j7X7F
                    )}
                  >
                    {"RTD Cocktail Development"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8ShBo
                  )}
                >
                  {"Libertine Cocktail Bar, Barcelona"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jwi92
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__kqpDx
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__rvxFh
                          )}
                        >
                          {"Bar concept creation"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xh1T9
                          )}
                        >
                          {"Menu creation & curation"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__onuck
                          )}
                        >
                          {
                            "Draft, bottled, and canned cocktail program creation"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___59RLr
                          )}
                        >
                          {"Team training"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"tiberiProject"}
                data-plasmic-override={overrides.tiberiProject}
                className={classNames(projectcss.all, sty.tiberiProject)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__gsWX)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/whiteBar.png",
                    fullWidth: 632,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ief9L)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__saGc1
                    )}
                  >
                    {"Bar Programs"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4VU0T
                    )}
                  >
                    {"RTD Cocktail Development"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sgFWe
                  )}
                >
                  {"Tiberi, Barcelona"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lPlHq
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__ghaym
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__mgloE
                          )}
                        >
                          {"Draft cocktail program"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__zXhEw
                          )}
                        >
                          {"Sourcing of materials"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__t1KRh
                          )}
                        >
                          {"Installation oversight"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"whiskeriaProject"}
                data-plasmic-override={overrides.whiskeriaProject}
                className={classNames(projectcss.all, sty.whiskeriaProject)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qCRw0)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/darkBar.png",
                    fullWidth: 634,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6RlZy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xy0XH
                    )}
                  >
                    {"Bar Programs"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mtSKl
                  )}
                >
                  {"La Whiskeria, Barcelona"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tdQf
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__iJcOb
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__mcRfm
                          )}
                        >
                          {"Cocktail menu development & curation"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__eBdc
                          )}
                        >
                          {"Standard operating procedure"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___1Iwwe
                          )}
                        >
                          {"Team training"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"twoSchmukcs"}
                data-plasmic-override={overrides.twoSchmukcs}
                className={classNames(projectcss.all, sty.twoSchmukcs)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__oj81H)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/stoneBar.png",
                    fullWidth: 632,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qdgKm)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dwEa
                    )}
                  >
                    {"Bar Programs"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tNpZ1
                  )}
                >
                  {"Two Schmucks, Barcelona"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Re97
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__mqYv
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__tzOMj
                          )}
                        >
                          {"Draft cocktail program"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___76GMo
                          )}
                        >
                          {"Standard operating procedure"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__a67Tl
                          )}
                        >
                          {"Team training"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"creativeColabsProject"}
                data-plasmic-override={overrides.creativeColabsProject}
                className={classNames(
                  projectcss.all,
                  sty.creativeColabsProject
                )}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eCpI0)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/unstackedCans.png",
                    fullWidth: 632,
                    fullHeight: 388,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fbXj3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2C8BR
                    )}
                  >
                    {"RTD Cocktail Development"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ot37W
                  )}
                >
                  {"Creative Collaborations"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0GEbh
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul___3Hz84
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__ftRwZ
                          )}
                        >
                          {"Hotel Casa Bonay"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__aBeL1
                          )}
                        >
                          {"Asia's 50 Best Bars"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__kv4X
                          )}
                        >
                          {"Wozere Studio"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xEj6W
                          )}
                        >
                          {"Michter's Whiskey"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"servicesSection"}
            data-plasmic-override={overrides.servicesSection}
            className={classNames(projectcss.all, sty.servicesSection)}
            id={"services"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mj14Y
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___9FxNk
                    )}
                  >
                    {"Services"}
                  </h5>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xPeC3)}>
              <div
                data-plasmic-name={"service1"}
                data-plasmic-override={overrides.service1}
                className={classNames(projectcss.all, sty.service1)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__h7OxU)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "329px"
                      : "271px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/rocksGlass.png",
                    fullWidth: 658,
                    fullHeight: 466,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dB1Oa)}
                >
                  <div
                    data-plasmic-name={"rtdProductDevelopment"}
                    data-plasmic-override={overrides.rtdProductDevelopment}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.rtdProductDevelopment
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___8Iewq
                          )}
                        >
                          {"RTD PRODUCT DEVELOPMENT"}
                        </h5>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g7CNt
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <ul
                          className={classNames(
                            projectcss.all,
                            projectcss.ul,
                            sty.ul__fpw3Y
                          )}
                        >
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__eeX4
                            )}
                          >
                            {"Concept ideation to full formulation"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__wb3Ss
                            )}
                          >
                            {
                              "Ingredient sourcing, flavor development, and recipe creation"
                            }
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__u0WTy
                            )}
                          >
                            {
                              "Scaling up from test kitchen to production facility"
                            }
                          </li>
                        </ul>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <LineBreakIcon
                    className={classNames(projectcss.all, sty.svg__j2GYc)}
                    role={"img"}
                  />
                </Stack__>
              </div>
              <div
                data-plasmic-name={"service2"}
                data-plasmic-override={overrides.service2}
                className={classNames(projectcss.all, sty.service2)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mCU7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "329px"
                      : "271px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/barsAndTablesRound.png",
                    fullWidth: 657,
                    fullHeight: 466,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hn71T)}
                >
                  <div
                    data-plasmic-name={"rtdProductDevelopment2"}
                    data-plasmic-override={overrides.rtdProductDevelopment2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.rtdProductDevelopment2
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___7KDF
                          )}
                        >
                          {"BAR PROGRAM CONSULTING"}
                        </h5>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j7OBc
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <ul
                          className={classNames(
                            projectcss.all,
                            projectcss.ul,
                            sty.ul__d8Vjv
                          )}
                        >
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__dqOu6
                            )}
                          >
                            {"Concept creation"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__slm8A
                            )}
                          >
                            {"Menu development and costing"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__sveei
                            )}
                          >
                            {"Signature drinks"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li___3DcUx
                            )}
                          >
                            {"Draft, bottled, and canned cocktail solutions"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__f5Hsg
                            )}
                          >
                            {"Staff training"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__nkhOj
                            )}
                          >
                            {"SOP creation and operational consulting"}
                          </li>
                        </ul>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <LineBreakIcon
                    className={classNames(projectcss.all, sty.svg__lmffA)}
                    role={"img"}
                  />
                </Stack__>
              </div>
              <div
                data-plasmic-name={"service3"}
                data-plasmic-override={overrides.service3}
                className={classNames(projectcss.all, sty.service3)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__exN01)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "329px"
                      : "271px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/cocktailWithLeaves.png",
                    fullWidth: 658,
                    fullHeight: 466,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4Usfl)}
                >
                  <div
                    data-plasmic-name={"rtdProductDevelopment3"}
                    data-plasmic-override={overrides.rtdProductDevelopment3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.rtdProductDevelopment3
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__unVvz
                          )}
                        >
                          {"MENU CREATION"}
                        </h5>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rmjsM
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <ul
                          className={classNames(
                            projectcss.all,
                            projectcss.ul,
                            sty.ul__v107B
                          )}
                        >
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__pyJsk
                            )}
                          >
                            {"Seasonal cocktail menus"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__z3Y5T
                            )}
                          >
                            {"Signature drinks"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__gv5K3
                            )}
                          >
                            {"Branded or collaboration menus"}
                          </li>
                        </ul>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <LineBreakIcon
                    className={classNames(projectcss.all, sty.svg__tnB4I)}
                    role={"img"}
                  />
                </Stack__>
              </div>
              <div
                data-plasmic-name={"service4"}
                data-plasmic-override={overrides.service4}
                className={classNames(projectcss.all, sty.service4)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uFqoz)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "329px"
                      : "271px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/bottles.png",
                    fullWidth: 658,
                    fullHeight: 466,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wBuCn)}
                >
                  <div
                    data-plasmic-name={"rtdProductDevelopment4"}
                    data-plasmic-override={overrides.rtdProductDevelopment4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.rtdProductDevelopment4
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__zC0Z
                          )}
                        >
                          {"CREATIVE COLLABORATION"}
                        </h5>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eqc3E
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <ul
                          className={classNames(
                            projectcss.all,
                            projectcss.ul,
                            sty.ul__eq7JU
                          )}
                        >
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__qYn8B
                            )}
                          >
                            {"Brand activations and pop-ups\n"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li___2KhkC
                            )}
                          >
                            {"Customized cocktail creation"}
                          </li>
                          <li
                            className={classNames(
                              projectcss.all,
                              projectcss.li,
                              projectcss.__wab_text,
                              sty.li__ai435
                            )}
                          >
                            {"Private or immersive cocktail experiences"}
                          </li>
                        </ul>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerSection",
    "h1",
    "button",
    "aboutMeSection",
    "h4",
    "portfolioSection",
    "h6",
    "libertineBlendsProject",
    "libertineCocktailBarProject",
    "tiberiProject",
    "whiskeriaProject",
    "twoSchmukcs",
    "creativeColabsProject",
    "servicesSection",
    "service1",
    "rtdProductDevelopment",
    "service2",
    "rtdProductDevelopment2",
    "service3",
    "rtdProductDevelopment3",
    "service4",
    "rtdProductDevelopment4"
  ],
  headerSection: ["headerSection", "h1", "button"],
  h1: ["h1"],
  button: ["button"],
  aboutMeSection: ["aboutMeSection", "h4"],
  h4: ["h4"],
  portfolioSection: [
    "portfolioSection",
    "h6",
    "libertineBlendsProject",
    "libertineCocktailBarProject",
    "tiberiProject",
    "whiskeriaProject",
    "twoSchmukcs",
    "creativeColabsProject"
  ],
  h6: ["h6"],
  libertineBlendsProject: ["libertineBlendsProject"],
  libertineCocktailBarProject: ["libertineCocktailBarProject"],
  tiberiProject: ["tiberiProject"],
  whiskeriaProject: ["whiskeriaProject"],
  twoSchmukcs: ["twoSchmukcs"],
  creativeColabsProject: ["creativeColabsProject"],
  servicesSection: [
    "servicesSection",
    "service1",
    "rtdProductDevelopment",
    "service2",
    "rtdProductDevelopment2",
    "service3",
    "rtdProductDevelopment3",
    "service4",
    "rtdProductDevelopment4"
  ],
  service1: ["service1", "rtdProductDevelopment"],
  rtdProductDevelopment: ["rtdProductDevelopment"],
  service2: ["service2", "rtdProductDevelopment2"],
  rtdProductDevelopment2: ["rtdProductDevelopment2"],
  service3: ["service3", "rtdProductDevelopment3"],
  rtdProductDevelopment3: ["rtdProductDevelopment3"],
  service4: ["service4", "rtdProductDevelopment4"],
  rtdProductDevelopment4: ["rtdProductDevelopment4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerSection: "section";
  h1: "h1";
  button: typeof Button;
  aboutMeSection: "section";
  h4: "h4";
  portfolioSection: "section";
  h6: "h6";
  libertineBlendsProject: "div";
  libertineCocktailBarProject: "div";
  tiberiProject: "div";
  whiskeriaProject: "div";
  twoSchmukcs: "div";
  creativeColabsProject: "div";
  servicesSection: "section";
  service1: "div";
  rtdProductDevelopment: "div";
  service2: "div";
  rtdProductDevelopment2: "div";
  service3: "div";
  rtdProductDevelopment3: "div";
  service4: "div";
  rtdProductDevelopment4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerSection: makeNodeComponent("headerSection"),
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    aboutMeSection: makeNodeComponent("aboutMeSection"),
    h4: makeNodeComponent("h4"),
    portfolioSection: makeNodeComponent("portfolioSection"),
    h6: makeNodeComponent("h6"),
    libertineBlendsProject: makeNodeComponent("libertineBlendsProject"),
    libertineCocktailBarProject: makeNodeComponent(
      "libertineCocktailBarProject"
    ),
    tiberiProject: makeNodeComponent("tiberiProject"),
    whiskeriaProject: makeNodeComponent("whiskeriaProject"),
    twoSchmukcs: makeNodeComponent("twoSchmukcs"),
    creativeColabsProject: makeNodeComponent("creativeColabsProject"),
    servicesSection: makeNodeComponent("servicesSection"),
    service1: makeNodeComponent("service1"),
    rtdProductDevelopment: makeNodeComponent("rtdProductDevelopment"),
    service2: makeNodeComponent("service2"),
    rtdProductDevelopment2: makeNodeComponent("rtdProductDevelopment2"),
    service3: makeNodeComponent("service3"),
    rtdProductDevelopment3: makeNodeComponent("rtdProductDevelopment3"),
    service4: makeNodeComponent("service4"),
    rtdProductDevelopment4: makeNodeComponent("rtdProductDevelopment4"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
